- .github/workflows/actions.yaml
- package-lock.json
- package.json
- src/components/Home.jsx
- src/tests/SimpleSampleTest.test.jsx
- Lagt till ett workflow för github actions frontend. Det som kommer ske när vi mergar en pull request till dev eller main grenen är enkelt förklarat bygger ihop och testar. Mer om flödet kan utläsas i actions.yaml filen.
- Byt till till denna branchen och gör någon ändring någonstans, en test kommentar eller nått. Sedan gör en commit och push, byt över till repot och gå in på branchen sedan Actions. Där inne borde det se ut ungefär såhär:
- Synpunkter?
> 1 ci pipeline frontend

- src/components/Login.jsx
Registrera användare
Frontend:
* knapp för att återgå till /home i login page om man vill registrera en ny användare.
- git checkout 11-login_page
- kolla att Return knappen funkar och att den navigerar dig till första sidan.
- Recenserare: 1 
* lämna kommentar på funktion för önskad ändring.
--
Closes #4
> return link to home in /login url

- src/components/AdminDashboard.jsx
- src/components/Dashboard.css
- src/components/Logout.css
- src/components/Logout.jsx
- src/components/UserDashboard.jsx
- src/components/dashboard/ButtonLink.css
- src/components/dashboard/ButtonLink.jsx
- Skapat dynamiska knappar till patient och vårdgivar dashboard. Knapparna är enkla att lägga till om det behövs fler och varje knapp tar emot picture som är länk till en bild, linkName som bara är en namn sträng och link är en länk sträng som exempelvis "/login".
- Lagt till lite style på logout knappen.
- Logga in med en user å se så att knapparna är där och inte ser skräp ut. Alla knappar har inte fått en unik bild än vilket vi får lägga till senare och samma med en kopplad länk. En user är "johan" "Johan123".
- Logga in med en vårdgivare "admin". Samma test där egentligen. En admin är "pedro" "pedro1".
- Denna PR gäller för 2 st issues. #3 #5
> 14 startpage patient

- src/App.jsx
- src/components/AdminDashboard.jsx
- src/components/Login.jsx
- src/components/Profile/Caregiver_profile.jsx
- src/components/Profile/Profile.jsx
- src/components/Signup/Signup.jsx
- src/components/UserDashboard.jsx
- src/components/footer/Footer.jsx
- navigate istället för href
- buttons istället för link
- importerar i enbart app istället för överallt
- ej synlig vid "/login", "/signup", "/"
- visar ej den knapp som man står vid, tex om man är på profile så syns inte profile
- hämtar inloggad användares roll från "/auth/check" för att visa rätt. (admin och user har inte alltid samma)
- returnerar null om användarens roll inte kan laddas
- tagit bort importer från de sidor som inte längre kräver import 
- refresh vid login för att kunna ladda rollbaserad footer
- Funktion genom att klicka runt lite och gör oväntade saker
- Några fler sidor som vi vill ska blockeras? isåfall fråga på discord innan du ändrar koden.
Close #19
> 19 fix footer

- src/App.jsx
error fix bcuz calendar was imported twice in app
> error fix app

- src/components/forgotPassword/ForgotPassword.jsx
- src/components/resetPassword/ResetPassword.jsx
(INFO! Innan denna PR kan göras måste  PR: multiple resetPasswordtokens with different mails #48  vara mergad in i backend.)
- Fil: ResetPassword.jsx
- Lagt till krav på nytt lösenord för user.
Testa att skapa ett lösenord utan att ha dessa symboler med 
"Password must be 8-20 characters, include uppercase, lowercase, and a number"
Closes #22
> added password requirements to reset password

- package-lock.json
- package.json
- src/App.jsx
- src/components/Appointment-info/A_info.css
- src/components/Appointment-info/A_info.jsx
- src/components/Profile/Profile.jsx
- src/components/footer/Footer.jsx
- vite.config.js
- en sida för mer detaljerad info om ens appointment
- "/appointment/info/{appointmentId} (man kommer hit efter man klickat på en appointment i listan som Matti gör)
- admin kan:
* cancel appointment om det är längre bort än 24h
* edit appointment to COMPLETED eller SCHEDULED om det är längre bort än 24h
* cancel, om appointment är inom 24h kan man inte cancel utan då får man skriva ett mail med subject och text till patientet
* edit, om appointment är inom 24h kan man inte cancel utan då får man skriva ett mail med subject och text till patientet
- user kan:
* cancel appointment om den är längre bort än 24h
* cancel- om appointment är inom 24h kan man skicka en mail request till caregiver, denna mail kommer till den som är angiven till ditt konto
* edit appointment -  enbart be om mail …
> 25 edit meeting schedule

- src/App.jsx
- src/components/DoctorDashboard.jsx
- src/components/Header.jsx
- src/components/Login.jsx
- src/components/Signup/Signup.jsx
- src/components/footer/Footer.jsx
Justerade sidor, header, footer efter den nya rollen Doctor
logga in som user
logga in som admin
logga in som doctor
testa runt
Closes #47
> doctor role

- src/App.jsx
- src/components/AdminDashboard.jsx
- src/components/UnderConstructionPage.jsx
- src/components/UserDashboard.jsx
- src/components/appointments/DoctorAppointent.jsx
- src/components/appointments/UserAppointment.css
- src/components/appointments/UserAppointment.jsx
What i did :
I create a Upcoming Meetings list for patient and for doctor with a simple css design. 
What to test :
To test it you have to use both branches backend and frontend.
Forntend : 30-list_of_incomingmeetings 
Backend branch: apotmintlistv2
You have to test both  patient and  doctor
use pedro for doctor
go to appointment and check if you find a list for doctor, and then login with your  account check if you find a list.
check if everything looks good.
3) 
when you click in list it will send you to info side
> 30 list of incomingmeetings

- src/components/AdminDashboard.jsx
- src/components/DoctorDashboard.jsx
- src/components/Profile/Caregiver_profile.jsx
- src/components/Profile/Profile.jsx
- src/components/UserDashboard.jsx
- src/components/footer/Footer.jsx
fixat:
* Header
* Footer
* Dashboards
vad är kvar:
* Profiler
* uppdatera databasen!!
3x testare
Closes #52
> länkar fixade för roll: doctor

- src/components/Appointment-info/A_info.css
- src/components/Appointment-info/A_info.jsx
Jag har satt en kolla på vilken roll man har, är man doctor syns edit knappen, är man en user så syns den inte
Testa att logga in på en user för att se så att det inte finns en edit knapp när du har klickat dig in på mer info i kommande möten.
testa samma sak fast att den nu istället syns när du är inloggad som Doktor
skriv om ni kommer på något
> 56 delete edit button in scheduled meeting

- src/components/Appointment-info/A_info.jsx
- src/components/Calendar/Calendar.jsx
- src/components/feedback/Feedback.jsx
- src/pages/appointmentHistory/AppointmentHistory.css
- src/pages/appointmentHistory/AppointmentHistory.jsx
- Justerat allt annat i frontend till att använda **reason** pga ändringarna i backend.
- Allmänt se att möten som har det nya värdet visas korrekt i frontend.
- Boka ett möte och se att det skapas med **reason** i databasen.
- Möteshistorik
- Inkommande möten
- Feedback
- Förhoppningsvis har jag inte missat något.
- Denna branchen samkörs med backend PR "**changed summary for reason #90**"
- Mergas tillsammans med backend PR
> 55 change name of summary

- src/components/Calendar/Calendar.jsx
What's done
added so you have to choose doctor before choosing time
added so you can see information about doctor
What to test
Log in as user and try to book an appointment and see if i missed anything or if it looks bad,
other: reviewers 1
connected to backend branch : changeBookDoctorBackend
> Book doctor changes

- src/App.jsx
- src/components/AdminDashboard.jsx
- src/components/DoctorDashboard.jsx
- src/components/Profile/Profile.jsx
- src/components/UserDashboard.jsx
Added logic to profile to fetch, load and display logged in accounts profile picture.
Log in as a user, doctor or admin. update profile picture on dashboard, navigate to profile. tada.
If no profile picture uploaded, an explaining alt-text will say: Upload Profile Picture To See It Here
Also added a n invicible footer att the bottom of profile and dashboard to bring content upwards. 
Closes #64
> 64 update ppic profile

- src/pages/appointmentHistory/AppointmentHistory.jsx
fixed appointment history for doctor
log in to pedro and it will load his appointment history
> fixed appointment history for doctor

- src/components/feedback/Feedback.jsx
- src/pages/appointmentHistory/AppointmentHistory.css
- src/pages/appointmentHistory/AppointmentHistory.jsx
- Doktor:
Inne i möteshistoriken kan en doktor lägga till dokumentation till ett avklarat möte. Dokumentation är en beskrivning från doktorns om hur mötet gick.
- Patient:
Inne i möteshistoriken kan patienten se om doktorn har angivit en dokumentation om det avklarade mötet.
- Lägga till dokumentation.
- Logga in som doktor.
- Gå till möteshistoriken.
- Se om det finns ett avklarat möte som inte har fått någon dokumentation.
- Lägg till dokumentation.
- Knappen "Add dokumentation" bör försvinna och den nya infon visas.
- Logga in som patienten som doktorn gav dokumentation till och kolla i möteshistoriken att den finns där.
- **VIKTIGT** Beroende av backend PR " **Add documentation to appointment method created with tests. #94** "
> 69 sjukjournal v1

- src/components/feedback/Feedback.css
- src/components/feedback/Feedback.jsx
- Lagt till pagination till feedback sidan.
- Logga in med pedro och en admin så kan man testa att byta sida.
- **OBS** Allt verkar funka men om man loggar in med pepsi och kollar feedback så vill inte sidan riktigt funka och det tror jag har att göra med felaktigheter i databasen så det kanske är dags att nuka den.
> added pagination

- src/components/Home.jsx
- src/components/doctorShowOff/DoctorShowOff.css
- src/components/doctorShowOff/DoctorShowOff.jsx
- src/components/feedback/Feedback.jsx
- En ny komponent till Home.jsx som hämtar och visar en slumpad lista med dem bästa betygen till våra doktorer.
Visar två åt gången om det finns, annars en. Rullar automatiskt med en 8 sekunders intervall.
- Ta en kik på hemsidan innan du ens loggar in eller reggar dig.
- **VIKTIGT** beroende av  "**Doctor show off #102**" i backend. 
- Synpunkter på design eller intervall?
> 44 add doctor showing off on start page login

- src/components/Schedule/Schedule.jsx
Whats done:
Added an extra form to the schedule page that you can pick multiple times to add to a day.
It sorts by time aswell.
The add -time slot filters out existing time slots for that day.
What to test:
Log in with doctor, go to schedule and add and remove as many timeslots as you want
Other: Reviewer 1
> Add available times doctor

- src/App.jsx
- src/components/AdminDashboard.jsx
- src/components/Signup/adminSignup/AdminSignup.css
- src/components/Signup/adminSignup/AdminSignup.jsx
- src/components/Signup/caregiverSignup/CaregiverSignup.jsx
- src/components/footer/Footer.jsx
What i did :
Created a new page for AdminSignup and caaregiverSignup.
Changed a footer path.
only admin can use this to pages.
______
What to test:
* test the footer path 
* test to create an admin and a caregiver
* test if you have successfully created and admin and a caregiver
> 49 register new doctoradmin

- src/components/Appointment-info/A_info.jsx
Changed so that you can change status all the time now instead
> Changed incoming appointments A-Info

- src/components/AddCondition.jsx
- Lagt till enums i frontend
- Testa med backend PR
> added more enums

- src/components/feedback/Feedback.jsx
> Feedback fix

- src/components/feedback/Feedback.jsx
Fixade ett problem till med givenFeedback
> Feedback fix 2

- src/components/DoctorDashboard.jsx
Tagit bort kalender knapp i doktor dashboard
> deleted calendar button doctor

- src/components/Profile/Profile.jsx
logga in som doctor och kolla så average grade är samma på your feedback som profile
> fixed grade for doctor

- src/components/appointments/UserAppointment.jsx
- src/pages/appointmentHistory/AppointmentHistory.jsx
added so if you don't have a history you get a text saying no appointments found
> Appointment history fix

- README.md
- src/components/Appointment-info/A_info.css
- src/components/Appointment-info/A_info.jsx
- src/components/Profile/Profile.jsx
- src/components/appointments/UserAppointment.jsx
- src/pages/appointmentHistory/AppointmentHistory.jsx
> Merge to Main
